[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "FootMimic"
author = "FootMimic Authors"
maintainer = "FootMimic Authors"
description = "Reference-guided command-conditioned humanoid football dribbling in Isaac Lab"
repository = "https://github.com/shaoyf0305/Footmimic.git"
keywords = ["isaaclab", "humanoid", "reinforcement-learning", "dribbling"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "soccer"

[isaaclab_settings]
# apt_deps = ["example_package"]
# ros_ws = "path/from/extension_root/to/ros_ws"
